server:
  port: 9999

spring:
  application:
    name: gateway9999
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': #拦截的请求
            allowedOrigins: #允许跨域的请求
              - "http://localhost:8080"
            allowedMethods: #运行跨域的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许请求中携带的头信息
            allowedCredentials: true #是否允许携带cookie
            maxAge: 36000 #跨域检测的有效期,单位s
      discovery:
        locator:
          enabled: true  # 开启注册中心动态创建路由的功能，利用服务进行路由
      routes:
        - id: user  # 用户服务
          uri: lb://user
          #          uri: http://localhost:8004
          predicates: # 断言 ，路径相匹配的进行路由
            - Path=/resource/**
          filters:
            - StripPrefix=1 # 去除前缀
        # ===================
        - id: image # 图片服务
          uri: lb://image-consumer
          #          uri: http://localhost:8001
          predicates: # 断言 ，路径相匹配的进行路由
            - Path=/image/**
          filters:
            - StripPrefix=1 # 去除前缀
        # ===================
        - id: video # 视频服务
          uri: lb://video-consumer
          #          uri: http://localhost:8002
          predicates: # 断言 ，路径相匹配的进行路由
            - Path=/video/**
          filters:
            - StripPrefix=1 # 去除前缀
        # ===================
        - id: note # 笔记服务
          uri: lb://note-consumer
#          uri: http://localhost:8003
          predicates:   # 断言 ，路径相匹配的进行路由
            - Path=/note/**
          filters:
            - StripPrefix=1 # 去除前缀
        # ===================
  redis:
    host: localhost
#    host: 192.168.18.128
    port: 6379
#    password: redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s


