server:
  port: 7003
spring:
  application:
    name: note-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_resource_manage?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml